name: linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux-test:
    runs-on: ubuntu-latest

    steps:
      # actionのバージョンを指定
      # TODO: 最適なバージョンを調べる
      - uses: actions/checkout@v2

      # Error Check
      - name: Run install.sh
        run: sh ${GITHUB_WORKSPACE}/install.sh

      - name: Run link.sh
        run: sh ${GITHUB_WORKSPACE}/link.sh