name: macos

on:
  push:
    branches: [ main ]
    paths:
      - "install_for_mac.sh"
      - "link_for_zsh.sh"
      - "setup.sh"
  pull_request:
    branches: [ main ]

env:
  HOME: "/Users/runner/work/dotfiles"
  SHELL: "/bin/zsh"

jobs:
  macos-test:
    runs-on: macos-latest  # これはIntel Macの環境 (M1 Mac対応待ち)

    steps:
      # actionのバージョンを指定
      # TODO: 最適なバージョンを調べる
      - uses: actions/checkout@v2

      # Error Check
      - name: Run install_for_mac.sh (only install)
        run: . $GITHUB_WORKSPACE/install_for_mac.sh
        shell: zsh {0}

      - name: Run link_for_zsh.sh (only link)
        run: . $GITHUB_WORKSPACE/link_for_zsh.sh
        shell: zsh {0}

      - name: Run setup.sh (install and link)
        run: . $GITHUB_WORKSPACE/setup.sh
        shell: zsh {0}