name: macos

on:
  push:
    branches: [ main ]
    paths:
      - "**.sh"
  pull_request:
    branches: [ main ]
    paths:
      - "**.sh"

jobs:
  macos-test:
    runs-on: macos-latest  # これはIntel Macの環境 (M1 Mac対応待ち)

    steps:
      # actionのバージョンを指定
      # TODO: 最適なバージョンを調べる
      - uses: actions/checkout@v2

      # Error Check
      - name: Run install_for_mac.sh (only install)
        run: sh $GITHUB_WORKSPACE/install_for_mac.sh
        shell: zsh {0}

      - name: Run link_for_zsh.sh (only link)
        run: sh $GITHUB_WORKSPACE/link_for_zsh.sh
        shell: zsh {0}

      - name: Run setup.sh (install and link)
        run: sh $GITHUB_WORKSPACE/setup.sh
        shell: zsh {0}