name: macos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  HOME: $GITHUB_WORKSPACE

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
      # actionのバージョンを指定
      # TODO: 最適なバージョンを調べる
      - uses: actions/checkout@v2
        with:
          path: $HOME

      # Error Check
      - name: Run install_for_mac.sh
        run: sh ${GITHUB_WORKSPACE}/install_for_mac.sh

      - name: Run link.sh
        run: sh ${GITHUB_WORKSPACE}/link.sh