name: macos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  HOME: "$HOME/work/${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}"

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
      # actionのバージョンを指定
      # TODO: 最適なバージョンを調べる
      - uses: actions/checkout@v2

      - name: locate HOME
        run: echo $HOME

      # Error Check
      - name: Run install_for_mac.sh
        run: sh $GITHUB_WORKSPACE/install_for_mac.sh

      - name: Run link.sh
        run: sh $GITHUB_WORKSPACE/link.sh