name: macos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos-test:
    runs-on: m1max

    steps:
      # actionのバージョンを指定
      # TODO: 最適なバージョンを調べる
      - uses: actions/checkout@v2

      # Error Check
      - name: Run install_for_mac.sh
        run: sh $GITHUB_WORKSPACE/install_for_mac.sh
        shell: zsh {0}

      - name: Run link.sh
        run: sh $GITHUB_WORKSPACE/link.sh
        shell: zsh {0}