name: ubuntu

on:
  push:
    branches: [ main ]
    paths:
      - "**.sh"
  pull_request:
    branches: [ main ]
    paths:
      - "**.sh"
env:
  HOME: "/Users/runner/work/dotfiles"
  SHELL: "/usr/bin/bash"

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest

    steps:
      # actionのバージョンを指定
      # TODO: 最適なバージョンを調べる
      - uses: actions/checkout@v2

      # Error Check
      - name: Run install_for_ubuntu.sh (only install)
        run: sh ${GITHUB_WORKSPACE}/install_for_ubuntu.sh
        shell: bash

      - name: Run link_for_bash.sh (only link)
        run: sh ${GITHUB_WORKSPACE}/link_for_bash.sh
        shell: bash

      - name: Run setup.sh (install and link)
        run: sh ${GITHUB_WORKSPACE}/setup.sh
        shell: bash