name: ubuntu

on:
  push:
    branches: [ main ]
    paths:
      - "install_for_ubuntu.sh"
      - "link_for_bash.sh"
  pull_request:
    branches: [ main ]
    paths:
      - "install_for_ubuntu.sh"
      - "link_for_bash.sh"
env:
  HOME: "/home/runner/work/dotfiles"
  SHELL: "/bin/bash"

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest

    steps:
      # actionのバージョンを指定
      # TODO: 最適なバージョンを調べる
      - uses: actions/checkout@v2

      - name: check bash
        run: command -v bash

      # Error Check
      - name: Run install_for_ubuntu.sh (only install)
        run: . ${GITHUB_WORKSPACE}/install_for_ubuntu.sh
        shell: bash

      - name: Run link_for_bash.sh (only link)
        run: . ${GITHUB_WORKSPACE}/link_for_bash.sh
        shell: bash

      - name: Run setup.sh (install and link)
        run: . ${GITHUB_WORKSPACE}/setup.sh
        shell: bash